version: '3.8'

services:
    dev:
        container_name: star_wars_api_dev
        image: star_wars_api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 4000:4000
            - 9229:9229
            - 5432:5432
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
            - /data/postgres:/data/postgres
        env_file:
            - docker.env
        restart: unless-stopped
    prod:
        container_name: star_wars_api_prod
        image: star_wars_api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 4000:4000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
networks:
  postgres:
    driver: bridge
    nesjs-network: